# Generated by Django 6.0.1 on 2026-01-24 12:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('team_created', 'Team Created'), ('member_joined', 'Member Joined'), ('round_started', 'Round Started'), ('page_completed', 'Page Completed'), ('round_completed', 'Round Completed'), ('bug_fixed', 'Bug Fixed'), ('time_over', 'Time Over')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Game Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bugs_fixed', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(choices=[(1, 'Round 1 - Stranger Things'), (2, 'Round 2 - One Piece'), (3, 'Round 3 - Squid Game')], unique=True)),
                ('is_open', models.BooleanField(default=False)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRoundProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('time_over', 'Time Over'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified')], default='not_started', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_qualified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['round__round_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='gameprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gameprogress',
            name='team',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='joinrequest',
            name='game_joinre_team_id_b6ab66_idx',
        ),
        migrations.RemoveField(
            model_name='teamactivity',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='current_page',
        ),
        migrations.RemoveField(
            model_name='team',
            name='current_round',
        ),
        migrations.RemoveField(
            model_name='team',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='max_members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_code',
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_password',
            field=models.CharField(default='defaultpassword', max_length=100),
        ),
        migrations.AddField(
            model_name='gameactivity',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='game.team'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='game.team'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamroundprogress',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progress', to='game.round'),
        ),
        migrations.AddField(
            model_name='teamroundprogress',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_progress', to='game.team'),
        ),
        migrations.AddField(
            model_name='pageprogress',
            name='team_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_progress', to='game.teamroundprogress'),
        ),
        migrations.DeleteModel(
            name='GameProgress',
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='team',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='TeamActivity',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='teamroundprogress',
            unique_together={('team', 'round')},
        ),
        migrations.AlterUniqueTogether(
            name='pageprogress',
            unique_together={('team_round', 'page_number')},
        ),
        migrations.DeleteModel(
            name='JoinRequest',
        ),
    ]
