# Generated by Django 6.0.1 on 2026-01-25 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameactivity_pageprogress_round_teammember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamroundprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('time_over', 'Time Over'), ('qualified', 'Qualified')], default='not_started', max_length=20),
        ),
    ]
